# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy -v
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - "6"
      - "7"
    binary: nacos-initial
    ldflags:
      - -v -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.builtDate={{.Date}}

dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    use: buildx
    ids:
      - build
    image_templates:
      - "docker.io/daixijun1990/nacos-initial:{{ .Tag }}"
      - "docker.io/daixijun1990/nacos-initial:v{{ .Major }}"
      - "docker.io/daixijun1990/nacos-initial:v{{ .Major }}.{{ .Minor }}"
      - "docker.io/daixijun1990/nacos-initial:latest"
      - "ghcr.io/daixijun/nacos-initial:{{ .Tag }}"
      - "ghcr.io/daixijun/nacos-initial:v{{ .Major }}"
      - "ghcr.io/daixijun/nacos-initial:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/daixijun/nacos-initial:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  github:
    owner: daixijun
    name: nacos-initial
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore"
