# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    # goos:
    #   - linux
    #   - darwin
    #   - windows
    # goarch:
    #   - amd64
    #   - arm
    #   - arm64
    # goarm:
    #   - 6
    #   - 7
    binary: nacos-initial
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.builtDate={{.Date}}
dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    image_templates:
      - "daixijun1990/nacos-initial:{{ .Tag }}"
      - "daixijun1990/nacos-initial:v{{ .Major }}"
      - "daixijun1990/nacos-initial:v{{ .Major }}.{{ .Minor }}"
      - "daixijun1990/nacos-initial:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      # 386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore"
